### ISSUE TITLE
`is_readable` returns false

### ISSUE THREAD

**Issue by azamat-sharapov** [adlawson/php-vfs#15]
Trying basic code from example, but `is_readable()` returns false, while `file_get_contents()` returns contents without problems. I assume this is because it's stream and looks like `is_readable()` returns false for streams. 

Any idea/workaround for this?

**Comment by adlawson** [comment]
Full ACL/permissions aren't supported, but I hadn't considered adding full permission bits on everything (you essentially have full access already, but the bits weren't set).

I've just added support for this in #16.
I'll merge them in a mo if that will fix the issues you're seeing?

**Comment by azamat-sharapov** [comment]
Wow, I think that should work! I was just writing some tests on PHP app and it's using symphony's MimeTypeGuesser, which uses is_readable. So that was stopping me using vfs. 

I'll be waiting for PR merge. Thanks!

**Comment by adlawson** [comment]
Okay, you should see the changes in version `0.12.0` :rocket:

**Comment by azamat-sharapov** [comment]
Ah, looks like [getPathName()](http://php.net/manual/en/splfileinfo.getpathname.php) doesn't work with vfs also.
But `is_readable()` worked, thank you again.
